# migrations/versions/069fa5c86847_....py

"""Add user favorite vocabulary relationship #<-- 这个描述可能不准确了，应该是 add source_book

Revision ID: 069fa5c86847
Revises: d812ab051828
Create Date: ...

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069fa5c86847'
down_revision = 'd812ab051828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 batch_alter_table 适用于 SQLite
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        # --- 修改这行：添加 server_default='2' ---
        batch_op.add_column(sa.Column('source_book', sa.Integer(), nullable=False, server_default='2'))
        # ------------------------------------------
        # 创建索引的操作保持不变
        batch_op.create_index(batch_op.f('ix_vocabulary_source_book'), ['source_book'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # downgrade 操作通常保持不变，确保它在 batch 模式下删除列和索引
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_source_book'))
        batch_op.drop_column('source_book')

    # ### end Alembic commands ###