"""Add marked_status_and_category_to_WrongAnswer

Revision ID: e6fe956cbfce
Revises: 3502ecb460c1
Create Date: 2025-04-17 19:45:34.902090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fe956cbfce'
down_revision = '3502ecb460c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_index('ix_user_is_admin')

    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.alter_column('english_word',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('chinese_translation',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=256),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_vocabulary_english_word'), ['english_word'], unique=False)

    with op.batch_alter_table('wrong_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_first_wrong', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_marked', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_wrong_answer_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_answer_is_marked'), ['is_marked'], unique=False)
        batch_op.create_index(batch_op.f('ix_wrong_answer_timestamp_first_wrong'), ['timestamp_first_wrong'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wrong_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wrong_answer_timestamp_first_wrong'))
        batch_op.drop_index(batch_op.f('ix_wrong_answer_is_marked'))
        batch_op.drop_index(batch_op.f('ix_wrong_answer_category'))
        batch_op.drop_column('category')
        batch_op.drop_column('is_marked')
        batch_op.drop_column('timestamp_first_wrong')

    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_english_word'))
        batch_op.alter_column('chinese_translation',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('english_word',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_is_admin', ['is_admin'], unique=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
